# Generated by Django 4.2.6 on 2023-10-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="quizQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, null=True)),
                ("question", models.TextField(max_length=100, null=True)),
                ("option1", models.CharField(max_length=100, null=True)),
                ("option2", models.CharField(max_length=100, null=True)),
                ("option3", models.CharField(max_length=100, null=True)),
                ("option4", models.CharField(max_length=100, null=True)),
                ("answer", models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
