# Generated by Django 4.2.6 on 2023-10-11 14:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizquestions",
            name="name",
        ),
    ]
