# Generated by Django 4.2.6 on 2023-10-16 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("quizApp", "0002_remove_quizquestions_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100, null=True)),
                ("author", models.CharField(max_length=100, null=True)),
                ("dt_date", models.DateTimeField(auto_now_add=True)),
                (
                    "quiz_name",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="related_quiz",
                        to="quizApp.quizquestions",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quizquestions",
            name="quiz",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="quizApp.quiz",
            ),
        ),
    ]
