# Generated by Django 4.2.6 on 2023-10-16 10:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quizApp", "0003_quiz_quizquestions_quiz"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="quiz_name",
            new_name="quiz",
        ),
    ]
