# Generated by Django 4.2.6 on 2023-10-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizApp", "0005_remove_quiz_quiz"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="quiz",
            field=models.IntegerField(null=True),
        ),
    ]
